name: env-continual

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.9
  - pip

  # Core scientific python
  - numpy
  - pandas
  - sparse

  # Plotting
  - matplotlib
  - seaborn

  # Machine Learning
  - pytorch::pytorch
  - pytorch::torchvision
  - cudatoolkit=11.3

  # pip requirements for git hosted package
  - pip:
      - wheel
      - buildtools
      - ray==1.7.0
      - ray[tune]
      - gdown==3.3.1
      - git+https://github.com/ContinualAI/avalanche.git
